# Embeddings Configuration
BATCH_SIZE: 128 
CHUNK_SIZE: 1000
CHUNK_OVERLAP: 200
EMBEDDING_MODEL: "text-embedding-3-small"
EMBEDDING_DIMENSION: 1536

# Models
CHAT_MODEL: "gpt-4o-2024-08-06"

# VectorStore 
PINECONE_CLOUD: "aws"
PINECONE_REGION: "us-east-1"

# Geocoding
GEOCODE_URL: "https://geocoding.geo.census.gov/geocoder/geographies/address"
GEOCODE_BENCHMARK: "Public_AR_Current"
GEOCODE_VINTAGE: "Current_Current"
