# Embeddings Configuration
EMBEDDING_DIMENSION: 1536

# Geocoding
GEOCODE_URL: "https://geocoding.geo.census.gov/geocoder/geographies/address"
GEOCODE_BENCHMARK: "Public_AR_Current"
GEOCODE_VINTAGE: "Current_Current"
