# Enter your API keys and save this file as config.yaml

# Technical Configuration
BATCH_SIZE: 128 
CHUNK_SIZE: 1000
CHUNK_OVERLAP: 200

# Models
CHAT_MODEL: "gpt-3.5-turbo"
EMBEDDING_MODEL: "text-embedding-3-small"
EMBEDDING_DIMENSION: 1536

# VectorStore 
PINECONE_INDEX_NAME: "lurlm"
PINECONE_NAMESPACE: "main"
PINECONE_CLOUD: "aws"
PINECONE_REGION: "us-east-1"
